stack:
  mtu: 1500
  subnet: 192.168.127.0/24
  gatewayIP: 192.168.127.1
  gatewayMacAddress: 5a:94:ef:e4:0c:dd
  dns:
    - name: containers.internal.
      records:
        - name: gateway
          ip: 192.168.127.1
        - name: host
          ip: 192.168.127.254
    - name: docker.internal.
      records:
        - name: gateway
          ip: 192.168.127.1
        - name: host
          ip: 192.168.127.254
    - name: revm.internal.
      records:
        - name: gateway
          ip: 192.168.127.1
        - name: host
          ip: 192.168.127.254
  nat:
    192.168.127.254: 127.0.0.1
  gatewayVirtualIPs:
    - 192.168.127.254
  dhcpStaticLeases:
    192.168.127.2: 5a:94:ef:e4:0c:ee
